name: "job_application_tracker"
services:
  postgres:
    image: postgres:17.4
    container_name: postgres_17_db
    restart: always
    env_file:
      - ../.env
    volumes:
      - ./data:/var/lib/postgresql/data:rw
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./logs:/var/log/postgresql:rw
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - db-network
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  db-network:
    driver: bridge
